### ISSUE TITLE
复选框 span 中文字超出一行时显示有问题

### ISSUE THREAD

**Issue by HereChen** [DXY-F2E/dxy-ui#2]
预览图直接在官方文档中添加的文字。文字超出一行，正常的话，要么居中靠前并且文字缩进，要么首行位置。

![image](https://user-images.githubusercontent.com/6745477/32836025-5cf6a6c8-ca43-11e7-973a-dad9c6fe282f.png)

**Comment by lwenn** [comment]
感谢提醒，近几天我们会修复这个问题~

**Comment by lwenn** [comment]
在刚发布的 `v1.0.1` 中已经修复了 @HereChen
